//
// Created by marius on 05.09.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_OPERATIONSCONTROLLER_HPP
#define GFORCE_TRAINER_CONTROLLER_OPERATIONSCONTROLLER_HPP


class OperationsController
{

};


#endif //GFORCE_TRAINER_CONTROLLER_OPERATIONSCONTROLLER_HPP
