//
// Created by marius on 29.08.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_MESSAGEFACTORY_HPP
#define GFORCE_TRAINER_CONTROLLER_MESSAGEFACTORY_HPP


class MessageFactory
{

};


#endif //GFORCE_TRAINER_CONTROLLER_MESSAGEFACTORY_HPP
