//
// Created by marius on 28.08.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_SOCKETINTERFACE_HPP
#define GFORCE_TRAINER_CONTROLLER_SOCKETINTERFACE_HPP

#endif //GFORCE_TRAINER_CONTROLLER_SOCKETINTERFACE_HPP
