#ifndef GFORCE_TRAINER_CONTROLLER_ROTATIONDIRECTION_HPP
#define GFORCE_TRAINER_CONTROLLER_ROTATIONDIRECTION_HPP

namespace GForce::Processing
{
    enum RotationDirection{right, left};
}

#endif //GFORCE_TRAINER_CONTROLLER_ROTATIONDIRECTION_HPP
