//
// Created by marius on 28.08.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_CONTROLSTATUS_HPP
#define GFORCE_TRAINER_CONTROLLER_CONTROLSTATUS_HPP


class ControlStatus
{

};


#endif //GFORCE_TRAINER_CONTROLLER_CONTROLSTATUS_HPP
