//
// Created by marius on 28.08.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_MOVIDRIVESERVICE_HPP
#define GFORCE_TRAINER_CONTROLLER_MOVIDRIVESERVICE_HPP


class MoviDriveService
{

};


#endif //GFORCE_TRAINER_CONTROLLER_MOVIDRIVESERVICE_HPP
