//
// Created by marius on 29.08.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_LOGGERINTERFACE_HPP
#define GFORCE_TRAINER_CONTROLLER_LOGGERINTERFACE_HPP

#endif //GFORCE_TRAINER_CONTROLLER_LOGGERINTERFACE_HPP
