//
// Created by marius on 29.08.19.
//

#ifndef GFORCE_TRAINER_CONTROLLER_STANDARDLOGGER_HPP
#define GFORCE_TRAINER_CONTROLLER_STANDARDLOGGER_HPP


class StandardLogger
{

};


#endif //GFORCE_TRAINER_CONTROLLER_STANDARDLOGGER_HPP
